import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FD',
    },

    // Gradient Header - Compact design (inside ScrollView)
    headerGradient: {
        paddingTop: 60,
        paddingBottom: 50,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        marginTop: 0,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        fontWeight: '500',
    },

    // Stats Container - Compact design like devices page
    statsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        marginTop: -30,
        marginBottom: 20,
        gap: 12,
        flexWrap: 'wrap',
    },
    statCard: {
        width: '48%',
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        marginBottom: 0,
    },
    statIconCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    statValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },

    // Search Section - Compact
    searchSection: {
        paddingHorizontal: 20,
        marginBottom: 12,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    searchIcon: {
        marginRight: 12,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#1F2937',
        fontWeight: '500',
    },
    scrollView: {
        paddingTop: 12,
        paddingHorizontal: 20,
    },
    sectionContainer: {
        backgroundColor: '#FFF',
        borderRadius: 16,
        marginBottom: 12,
        overflow: 'hidden',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#FAFBFF',
    },
    sectionTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sectionDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#111',
    },
    sectionBody: {
        paddingTop: 0,
        paddingBottom: 12,
        paddingHorizontal: 12,
        borderTopWidth: 1,
        borderTopColor: '#F0F2F8',
    },
    loadingContainer: {
        alignItems: 'center',
        paddingVertical: 24,
    },
    loadingText: {
        marginTop: 10,
        fontSize: 14,
        color: '#888',
        fontWeight: '500',
    },
    emptyText: {
        textAlign: 'center',
        color: '#888',
        marginTop: 12,
        fontStyle: 'italic',
        fontSize: 14,
    },
    cardsContainer: {
        marginTop: 12,
    },
    requestCard: {
        backgroundColor: '#FAFBFF',
        borderRadius: 16,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: '#E8EAEF',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
    },
    cardContent: {
        padding: 14,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    deviceInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    deviceImage: {
        width: 56,
        height: 56,
        borderRadius: 12,
        marginRight: 14,
        backgroundColor: '#F0F0F0',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    deviceImagePlaceholder: {
        width: 56,
        height: 56,
        borderRadius: 12,
        marginRight: 14,
        backgroundColor: '#F3F4F6',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    deviceTextContainer: {
        flex: 1,
    },
    deviceName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1C1C1E',
        marginBottom: 5,
        letterSpacing: 0.2,
    },
    deviceCode: {
        fontSize: 13,
        color: '#8E8E93',
        fontWeight: '600',
    },
    userRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        paddingLeft: 2,
    },
    userText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
        flex: 1,
        fontWeight: '500',
    },
    dateRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingLeft: 2,
    },
    dateItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dateText: {
        fontSize: 13,
        color: '#666',
        marginLeft: 6,
        fontWeight: '600',
    },
    statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        alignSelf: 'flex-start',
    },
    statusText: {
        fontSize: 12,
        fontWeight: '700',
    },
    quickActions: {
        flexDirection: 'row',
        gap: 8,
        paddingHorizontal: 12,
        paddingBottom: 12,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    quickActionBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        borderRadius: 8,
        gap: 6,
    },
    approveBtn: {
        backgroundColor: '#34C759',
    },
    rejectBtn: {
        backgroundColor: '#FF3B30',
    },
    confirmBtn: {
        backgroundColor: '#007AFF',
    },
    quickActionText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: '700',
    },
    // Reject Modal
    rejectModal: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    rejectModalContent: {
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 20,
        width: '100%',
        maxWidth: 400,
    },
    rejectModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1C1C1E',
        marginBottom: 16,
    },
    rejectInput: {
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 12,
        padding: 12,
        fontSize: 15,
        color: '#1C1C1E',
        minHeight: 100,
        marginBottom: 16,
    },
    rejectModalActions: {
        flexDirection: 'row',
        gap: 10,
    },
    rejectModalBtn: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelBtn: {
        backgroundColor: '#F0F0F0',
    },
    cancelBtnText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#666',
    },
    submitBtn: {
        backgroundColor: '#FF3B30',
    },
    submitBtnText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFF',
    },
    // Modal Styles
    modalContainer: {
        flex: 1,
        backgroundColor: '#F8F9FD',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    modalHeaderGradient: {
        paddingTop: 55,
        paddingBottom: 8,
        paddingHorizontal: 20,
    },
    modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalHeaderTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        flex: 1,
        textAlign: 'center',
        marginHorizontal: 12,
    },
    modalScrollView: {
        flex: 1,
    },
    modalStatusSection: {
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 8,
        alignItems: 'center',
    },
    modalStatusBadge: {
        paddingHorizontal: 24,
        paddingVertical: 10,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    modalStatusText: {
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    modalSection: {
        paddingHorizontal: 20,
        marginBottom: 24,
    },
    modalSectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 12,
        letterSpacing: 0.3,
    },
    modalCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#F0F2F8',
    },
    modalDeviceCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        flexDirection: 'row',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#F0F2F8',
    },
    modalDeviceImage: {
        width: 100,
        height: 100,
        borderRadius: 14,
        backgroundColor: '#F3F4F6',
        marginRight: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    modalDeviceImagePlaceholder: {
        width: 100,
        height: 100,
        borderRadius: 14,
        backgroundColor: '#F3F4F6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    modalDeviceInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    modalDeviceName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 10,
        letterSpacing: 0.2,
    },
    modalInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        gap: 8,
    },
    modalInfoText: {
        fontSize: 14,
        color: '#6B7280',
        flex: 1,
        fontWeight: '500',
    },
    modalDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 4,
        gap: 10,
    },
    modalLabel: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '600',
        minWidth: 110,
    },
    modalValue: {
        fontSize: 15,
        color: '#1F2937',
        fontWeight: '600',
        flex: 1,
    },
    modalDivider: {
        height: 1,
        backgroundColor: '#E5E7EB',
        marginVertical: 14,
    },
    modalNoteRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 8,
    },
    modalNoteText: {
        fontSize: 14,
        color: '#1F2937',
        lineHeight: 20,
        paddingLeft: 28,
    },
    modalRejectCard: {
        backgroundColor: '#FEF2F2',
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        borderWidth: 1,
        borderColor: '#FEE2E2',
    },
    modalRejectText: {
        flex: 1,
        fontSize: 14,
        color: '#DC2626',
        lineHeight: 22,
        fontWeight: '500',
    },
    modalActionBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#FFFFFF',
        padding: 16,
        paddingBottom: 20,
        flexDirection: 'row',
        gap: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        elevation: 8,
    },
    modalActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        borderRadius: 12,
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },
    modalApproveButton: {
        backgroundColor: '#10B981',
    },
    modalRejectButton: {
        backgroundColor: '#EF4444',
    },
    modalConfirmButton: {
        backgroundColor: '#3B82F6',
    },
    modalActionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
});
