import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F7FF', padding: 16 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: 20, fontWeight: '700', color: '#0F172A' },
  menuBtn: { padding: 8 },
  menuDots: { fontSize: 22, color: '#475569' },
  menuOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  menuCard: { position: 'absolute', top: 56, right: 16, backgroundColor: '#fff', borderRadius: 8, elevation: 6, paddingVertical: 8, width: 200 },
  menuItem: { paddingVertical: 12, paddingHorizontal: 16 },
  menuText: { color: '#0F172A' },
  menuItemDestructive: { paddingVertical: 12, paddingHorizontal: 16, borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  menuTextDestructive: { color: '#DC2626', fontWeight: '700' },

  profileCard: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginTop: 16, elevation: 2 },
  avatarWrap: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#6366F1', alignItems: 'center', justifyContent: 'center' },
  avatarLetter: { color: '#fff', fontSize: 28, fontWeight: '700' },
  name: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  joined: { color: '#6B7280', marginTop: 4 },
  editSmall: { backgroundColor: '#EFF6FF', paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8 },
  editSmallText: { color: '#2563EB', fontWeight: '700' },

  infoRow: { marginTop: 12 },
  label: { color: '#6B7280', fontSize: 13 },
  value: { color: '#0F172A', fontWeight: '600', marginTop: 4 },
  changePwd: { marginTop: 14, paddingVertical: 10, alignItems: 'center', borderRadius: 8, backgroundColor: '#FEF3C7' },
  changePwdText: { color: '#92400E', fontWeight: '700' },

  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(15,23,42,0.4)' },
  modalCardLarge: { height: '78%', backgroundColor: '#fff', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16 },
  modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
  avatarEdit: { height: 92, borderRadius: 46, backgroundColor: '#4F46E5', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  avatarEditText: { color: '#fff', fontWeight: '700' },
  fieldLabel: { color: '#374151', marginBottom: 6, marginTop: 6 },
  input: { backgroundColor: '#F8FAFF', padding: 12, borderRadius: 10, borderWidth: 1, borderColor: '#E6EEF8' },
  caption: { color: '#9CA3AF', marginTop: 6, marginBottom: 6, fontSize: 12 },
  modalActionsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 },
  cancelButton: { flex: 1, padding: 12, borderRadius: 10, alignItems: 'center', marginRight: 8, backgroundColor: '#F3F4F6' },
  cancelText: { color: '#374151', fontWeight: '700' },
  saveButton: { flex: 1, padding: 12, borderRadius: 10, alignItems: 'center', marginLeft: 8, backgroundColor: '#10B981' },
  saveText: { color: '#fff', fontWeight: '700' },
  hint: { color: '#6B7280', marginBottom: 8 },

  bottomNav: { height: 64, backgroundColor: '#fff', borderRadius: 12, marginTop: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', elevation: 4 },
  navItem: { padding: 8 },
  navText: { color: '#6B7280' },
  navItemActive: { padding: 8 },
  navTextActive: { color: '#0F172A', fontWeight: '700' },
});