import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
        paddingHorizontal: 16,
    },
    header: {
        fontSize: 26,
        fontWeight: '700',
        color: '#1F2937',
        marginTop: 16,
        marginBottom: 12,
    },
    searchRow: {
        marginBottom: 12,
    },
    searchInput: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 15,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    tabRow: {
        flexDirection: 'row',
        marginBottom: 16,
        backgroundColor: '#E5E7EB',
        borderRadius: 10,
        padding: 4,
    },
    tabBtn: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 8,
    },
    tabActive: {
        backgroundColor: '#FFFFFF',
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6B7280',
    },
    tabTextActive: {
        color: '#1F2937',
        fontWeight: '600',
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    name: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    code: {
        fontSize: 13,
        color: '#6B7280',
    },
    actionBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        backgroundColor: '#F3F4F6',
    },
    actionText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#3B82F6',
    },
    caretBtn: {
        marginLeft: 8,
        padding: 6,
    },
    caretText: {
        fontSize: 14,
        color: '#9CA3AF',
    },
    cardBody: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F3F4F6',
    },
    label: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 6,
    },
    value: {
        fontWeight: '600',
        color: '#1F2937',
    },
    addBtn: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        backgroundColor: '#3B82F6',
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 8,
    },
    addBtnText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '600',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalCard: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
        maxHeight: '90%',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 16,
    },
    avatarPlaceholder: {
        height: 100,
        backgroundColor: '#9CA3AF',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    fieldLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
        marginTop: 12,
    },
    input: {
        backgroundColor: '#F9FAFB',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 15,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    optionRow: {
        flexDirection: 'row',
        marginTop: 8,
    },
    optionBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        alignItems: 'center',
        marginRight: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    optionActive: {
        backgroundColor: '#3B82F6',
        borderColor: '#3B82F6',
    },
    optionText: {
        fontSize: 13,
        fontWeight: '500',
        color: '#6B7280',
    },
    optionTextActive: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    modalActionsRow: {
        flexDirection: 'row',
        marginTop: 20,
    },
    modalActionBtn: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        marginHorizontal: 6,
    },
});
