import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FD',
    },

    // Header Gradient - Modern vibrant gradient
    headerGradient: {
        paddingTop: 60,
        paddingBottom: 55,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 35,
        borderBottomRightRadius: 35,
        shadowColor: '#5B21B6',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 10,
        letterSpacing: 0.5,
    },
    headerSubtitle: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.95)',
        fontWeight: '500',
    },

    // Stats Container - Glassmorphism cards
    statsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginTop: -35,
        marginBottom: 24,
        gap: 12,
    },
    statCard: {
        flex: 1,
        borderRadius: 20,
        padding: 18,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.8)',
    },
    statIconCircle: {
        width: 52,
        height: 52,
        borderRadius: 26,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    statValue: {
        fontSize: 26,
        fontWeight: '800',
        color: '#1F2937',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#6B7280',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },

    // Search Section - Modern glassmorphism
    searchSection: {
        paddingHorizontal: 24,
        marginBottom: 20,
    },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        paddingHorizontal: 18,
        paddingVertical: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.1)',
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#1F2937',
        fontWeight: '500',
    },

    // List
    listContent: {
        paddingHorizontal: 24,
        paddingBottom: 100,
    },
    loadingContainer: {
        padding: 50,
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 14,
        fontSize: 15,
        color: '#6B7280',
        fontWeight: '500',
    },
    emptyContainer: {
        padding: 70,
        alignItems: 'center',
    },
    emptyText: {
        fontSize: 17,
        fontWeight: '700',
        color: '#6B7280',
        marginTop: 18,
        marginBottom: 10,
    },
    emptySubtext: {
        fontSize: 14,
        color: '#9CA3AF',
        textAlign: 'center',
        fontWeight: '500',
    },

    // User Card - Modern glassmorphism
    userCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        marginBottom: 14,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.08)',
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 18,
        backgroundColor: '#FAFBFF',
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    avatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginRight: 14,
        borderWidth: 2,
        borderColor: 'rgba(99, 102, 241, 0.2)',
    },
    avatarPlaceholder: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
        borderWidth: 2,
        borderColor: '#E5E7EB',
    },
    userTextContainer: {
        flex: 1,
    },
    userName: {
        fontSize: 17,
        fontWeight: '800',
        color: '#1F2937',
        marginBottom: 5,
        letterSpacing: 0.2,
    },
    userEmail: {
        fontSize: 13,
        color: '#6B7280',
        fontWeight: '500',
    },
    cardActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statusBadgeActive: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 14,
        gap: 5,
        shadowColor: '#34C759',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
    statusTextActive: {
        fontSize: 12,
        fontWeight: '700',
        color: '#34C759',
        textTransform: 'uppercase',
        letterSpacing: 0.3,
    },
    statusBadgeLocked: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFEBEE',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 14,
        gap: 5,
        shadowColor: '#FF3B30',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 2,
    },
    statusTextLocked: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FF3B30',
        textTransform: 'uppercase',
        letterSpacing: 0.3,
    },

    // Expanded Content
    expandedContent: {
        paddingHorizontal: 18,
        paddingBottom: 18,
        borderTopWidth: 1,
        borderTopColor: '#F0F2F8',
        backgroundColor: '#FFFFFF',
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        gap: 10,
    },
    detailLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: '#6B7280',
        width: 110,
    },
    detailValue: {
        flex: 1,
        fontSize: 14,
        color: '#1F2937',
        fontWeight: '500',
    },
    lockButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FF3B30',
        paddingVertical: 14,
        borderRadius: 14,
        marginTop: 14,
        gap: 10,
        shadowColor: '#FF3B30',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    unlockButton: {
        backgroundColor: '#34C759',
        shadowColor: '#34C759',
    },
    lockButtonText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#FFFFFF',
        letterSpacing: 0.3,
    },
});
