import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#F7FAFC', padding: 16},
  title: {fontSize: 22, fontWeight: '700', marginBottom: 12, color: '#0F172A'},
  cardRow: {flexDirection: 'row', gap: 12, marginBottom: 16},
  cardLarge: {flex: 1, backgroundColor: '#FFFFFF', borderRadius: 12, padding: 12, shadowColor: '#000', elevation: 2},
  cardSmall: {width: 140, marginLeft: 12, backgroundColor: '#FFFFFF', borderRadius: 12, padding: 12, alignItems: 'center', justifyContent: 'center', elevation: 2},
  cardTitle: {fontSize: 14, fontWeight: '600', marginBottom: 8, color: '#1F2937'},
  centered: {alignItems: 'center'},
  pieCenterTextWrap: {position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, alignItems: 'center', justifyContent: 'center'},
  pieCenterPercent: {fontSize: 20, fontWeight: '700', color: '#0F172A'},
  pieCenterSub: {fontSize: 12, color: '#64748B'},
  legendRow: {flexDirection: 'row', alignItems: 'center', marginBottom: 8},
  legendColor: {width: 14, height: 14, borderRadius: 4, marginRight: 8},
  legendLabel: {fontSize: 13, color: '#0F172A', marginRight: 8},
  legendValue: {fontSize: 13, color: '#475569', marginLeft: 8},
  bigPercent: {fontSize: 28, fontWeight: '800', color: '#0F172A'},
  cardSub: {fontSize: 12, color: '#64748B'},
  filterRow: {marginVertical: 12},
  filterRowSmall: {marginBottom: 8},
  chip: {paddingVertical: 8, paddingHorizontal: 14, backgroundColor: '#fff', borderRadius: 999, marginRight: 8, borderWidth: 1, borderColor: '#E6E6E6'},
  chipActive: {backgroundColor: '#2563EB', borderColor: '#2563EB'},
  chipText: {color: '#0F172A', fontWeight: '600'},
  chipTextActive: {color: '#fff'},
  chipSmall: {paddingVertical: 6, paddingHorizontal: 12, backgroundColor: '#fff', borderRadius: 8, marginRight: 8, borderWidth: 1, borderColor: '#E6E6E6'},
  chipSmallActive: {backgroundColor: '#FB923C', borderColor: '#FB923C'},
  chipSmallText: {color: '#0F172A'},
  chipSmallTextActive: {color: '#fff'},
  listCard: {backgroundColor: '#fff', borderRadius: 12, padding: 12, marginBottom: 12, elevation: 1},
  sectionTitle: {fontSize: 16, fontWeight: '700', marginBottom: 8},
  itemRow: {flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9'},
  itemTitle: {fontWeight: '700'},
  itemSubtitle: {color: '#64748B', marginTop: 4},
  itemPercent: {fontSize: 16, fontWeight: '700'},
  itemSmall: {fontSize: 12, color: '#94A3B8'},
  recentRow: {flexDirection: 'row', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9'},
  recentTitle: {fontWeight: '700'},
  recentSub: {color: '#64748B', marginTop: 4},
  recentTime: {fontSize: 12, color: '#94A3B8'},
  recentStatus: {fontSize: 12, fontWeight: '600', marginTop: 6},
});
