import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FD',
    },
    headerGradient: {
        paddingTop: 60,
        paddingBottom: 55,
        paddingHorizontal: 24,
        borderBottomLeftRadius: 35,
        borderBottomRightRadius: 35,
        shadowColor: '#5B21B6',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
        marginBottom: 20,
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 10,
        letterSpacing: 0.5,
    },
    headerSubtitle: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.95)',
        fontWeight: '500',
    },

    // Stats Row - Compact design like devices page
    statsRow: {
        flexDirection: 'row',
        marginBottom: 16,
        flexWrap: 'wrap',
    },
    cardLarge: {
        flex: 2,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginRight: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    statCard: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    statIconCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#334155',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    statValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1F2937',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
        marginBottom: 2,
    },
    statSubLabel: {
        fontSize: 11,
        color: '#9CA3AF',
        fontWeight: '500',
    },

    // Chart Card - Modern glassmorphism
    chartCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 24,
        marginBottom: 20,
        marginHorizontal: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.08)',
    },
    chartTitle: {
        fontSize: 19,
        fontWeight: '800',
        color: '#1F2937',
        marginBottom: 24,
        letterSpacing: 0.3,
    },
    chartContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    pieWrapper: {
        position: 'relative',
        width: 180,
        height: 180,
        justifyContent: 'center',
        alignItems: 'center',
    },
    pieCenterText: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
    },
    pieCenterNumber: {
        fontSize: 28,
        fontWeight: '700',
        color: '#1F2937',
    },
    pieCenterLabel: {
        fontSize: 12,
        color: '#9CA3AF',
        marginTop: 2,
    },
    legendContainer: {
        flex: 1,
        marginLeft: 20,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
        width: '100%'
    },
    legendDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 8,
    },
    legendText: {
        flex: 1,
        fontSize: 13,
        color: '#4B5563',
        marginRight: 6,
        flex: 1,
    },
    legendCount: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1F2937',
        marginLeft: 8,
    },
    emptyChart: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyText: {
        fontSize: 14,
        color: '#9CA3AF',
        marginTop: 12,
    },

    // Top Devices Card - Modern glassmorphism
    topDevicesCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 24,
        marginBottom: 20,
        marginHorizontal: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.08)',
    },
    chipActive: {
        backgroundColor: '#3B82F6',
        borderColor: '#3B82F6',
    },
    chipText: {
        fontSize: 13,
        fontWeight: '500',
        color: '#6B7280',
    },
    chipTextActive: {
        color: '#FFFFFF',
    },
    chipSmall: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
        marginRight: 6,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        elevation: 1,
    },
    chipSmallActive: {
        backgroundColor: '#10B981',
        borderColor: '#10B981',
    },
    chipSmallText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#6B7280',
    },
    chipSmallTextActive: {
        color: '#FFFFFF',
    },
    cardFull: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },

    listCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 3,
    },

    /* Modal styles */
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: '92%',
        maxHeight: '80%',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        elevation: 4,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#111827',
    },
    modalClose: {
        color: '#6B7280',
        fontWeight: '600',
    },
    modalFilters: {
        marginBottom: 8,
    },
    modalTabs: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    tabBtn: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
        marginRight: 8,
    },
    tabBtnActive: {
        backgroundColor: '#3B82F6',
    },
    tabText: {
        color: '#6B7280',
        fontWeight: '600',
    },
    tabTextActive: {
        color: '#FFFFFF',
    },
    modalList: {
        flex: 1,
        marginTop: 8,
    },
    modalRow: {
        flexDirection: 'row',
        paddingVertical: 12,
        alignItems: 'center',
    },
    miniBar: {
        width: '100%',
        borderTopLeftRadius: 4,
        borderTopRightRadius: 4,
    },
    progressTrack: {
        height: 12,
        backgroundColor: '#E5E7EB',
        borderRadius: 999,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#34D399',
    },
    cardHeaderTitle: {
        fontSize: 19,
        fontWeight: '800',
        color: '#1F2937',
        marginLeft: 10,
        letterSpacing: 0.3,
    },
    deviceItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    deviceRank: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#334155',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    rankNumber: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFF',
    },
    deviceImageContainer: {
        width: 48,
        height: 48,
        borderRadius: 12,
        overflow: 'hidden',
        marginRight: 12,
        backgroundColor: '#F9FAFB',
    },
    metaText: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    itemPercent: {
        fontSize: 18,
        fontWeight: '700',
        color: '#3B82F6',
        marginBottom: 2,
    },
    deviceImagePlaceholder: {
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
    },
    statusSummary: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    statusItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8FAFC',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 12,
        marginRight: 8,
        marginBottom: 8,
    },
    deviceTypeCard: {
        backgroundColor: '#FFFFFF',
        borderColor: '#E5E7EB',
        borderWidth: 1,
        borderRadius: 8,
        padding: 10,
        marginRight: 8,
        marginBottom: 8,
        minWidth: 140,
        elevation: 1,
    },
    deviceTypeCardActive: {
        borderColor: '#3B82F6',
        backgroundColor: '#EFF6FF',
    },
    deviceTypeCardTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: '#111827',
    },
    deviceTypeCardMeta: {
        fontSize: 12,
        color: '#6B7280',
    },
    statusDot: {
        width: 10,
        height: 10,
        borderRadius: 3,
    },
    statusLabel: {
        fontSize: 12,
        color: '#374151',
        fontWeight: '600',
    },
    statusCount: {
        fontSize: 11,
        color: '#6B7280',
    },
    recentRow: {
        flexDirection: 'row',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    deviceName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    deviceCode: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    deviceCount: {
        alignItems: 'center',
        minWidth: 50,
    },
    countNumber: {
        fontSize: 20,
        fontWeight: '700',
        color: '#334155',
    },
    countLabel: {
        fontSize: 11,
        color: '#9CA3AF',
    },
});
